server:
  port: 9120

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka

spring:
  application:
    name: simple-module-sys
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      #url: jdbc:postgresql://192.168.1.166:7777/gs_wuye
      url: jdbc:postgresql://114.116.17.114:7777/simple_zhaipan
      username: jfwy
      password: tongruan@123
      #url: jdbc:postgresql://192.168.0.205:5432/gs_wuye
      #username: gs
      #password: jjxliu306
      initial-size: 10
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true



#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.zp.*.*.entity
logging:
  level:
    com.zp: debug
