#系统管理的配置文件
syslog:
  baseUrl: http://whois.pconline.com.cn/ipJson.jsp #IP转地址
  sysLog: #系统日志线程池配置
    corePoolSize: 5 #核心线程数
    maxPoolSize: 20 #最大线程数
    maxQueue: 100 #最大队列
    keepAlive: 120 #秒
  loginLog: #登录日志线程池配置
    corePoolSize: 5 #核心线程数
    maxPoolSize: 20 #最大线程数
    maxQueue: 100 #最大队列
    keepAlive: 120 #秒


logging:
  level:
    com.zp: debug