server:
  port: 9130
eureka:
  instance:
    hostname: simple-module-job
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #自己就是服务不检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  application:
    name: 定时任务
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      #url: jdbc:postgresql://192.168.1.166:7777/gs_wuye
      #url: jdbc:postgresql://114.116.17.114:7777/gs_wuye
      #username: jfwy
      #password: tongruan@123
      url: jdbc:postgresql://192.168.0.205:5432/gs_wuye
      username: gs
      password: jjxliu306
      initial-size: 10
      max-active: 30
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true